import * as Wi from "react-icons/wi";
import { WeatherConditions } from "../@types/forecast";

export const weatherConditionIcons = {
  1000: [Wi.WiNightClear, Wi.WiDaySunny],
  1003: [Wi.WiNightCloudy, Wi.WiDayCloudy],
  1006: [Wi.WiNightAltCloudyHigh, Wi.WiCloudy],
  1009: [Wi.WiNightAltPartlyCloudy, Wi.WiDaySunnyOvercast],
  1030: [Wi.WiNightFog, Wi.WiDayFog],
  1063: [Wi.WiNightHail, Wi.WiDayHail],
  1066: [Wi.WiNightSnow, Wi.WiDaySnow],
  1069: [Wi.WiNightSleet, Wi.WiDaySleet],
  1072: [Wi.WiSnowWind, Wi.WiSnowWind],
  1087: [Wi.WiNightLightning, Wi.WiDayLightning],
  1114: [Wi.WiSnowWind, Wi.WiSnowWind],
  1117: [Wi.WiSnowflakeCold, Wi.WiSnowflakeCold],
  1135: [Wi.WiFog, Wi.WiFog],
  1147: [Wi.WiSnowflakeCold, Wi.WiSnowflakeCold],
  1150: [Wi.WiRainMix, Wi.WiRainMix],
  1153: [Wi.WiRainWind, Wi.WiRainWind],
  1168: [Wi.WiSleet, Wi.WiSleet],
  1171: [Wi.WiShowers, Wi.WiShowers],
  1180: [Wi.WiNightRainMix, Wi.WiDayRainMix],
  1183: [Wi.WiRain, Wi.WiRain],
  1186: [Wi.WiNightRainMix, Wi.WiDayRainMix],
  1189: [Wi.WiRain, Wi.WiRain],
  1192: [Wi.WiNightRainMix, Wi.WiDayRainMix],
  1195: [Wi.WiRain, Wi.WiRain],
  1198: [Wi.WiRainWind, Wi.WiRainWind],
  1201: [Wi.WiRainWind, Wi.WiRainWind],
  1204: [Wi.WiSleet, Wi.WiSleet],
  1207: [Wi.WiSleet, Wi.WiSleet],
  1210: [Wi.WiNightSnow, Wi.WiDaySnow],
  1213: [Wi.WiSnow, Wi.WiSnow],
  1216: [Wi.WiSnow, Wi.WiSnow],
  1219: [Wi.WiSnow, Wi.WiSnow],
  1222: [Wi.WiSnowflakeCold, Wi.WiSnowflakeCold],
  1225: [Wi.WiSnowflakeCold, Wi.WiSnowflakeCold],
  1237: [Wi.WiSnowflakeCold, Wi.WiSnowflakeCold],
  1240: [Wi.WiNightRainMix, Wi.WiDayRainMix],
  1243: [Wi.WiNightRainMix, Wi.WiDayRainMix],
  1246: [Wi.WiNightThunderstorm, Wi.WiDayThunderstorm],
  1249: [Wi.WiSleet, Wi.WiSleet],
  1252: [Wi.WiSleet, Wi.WiSleet],
  1255: [Wi.WiSnowflakeCold, Wi.WiSnowflakeCold],
  1258: [Wi.WiSnowflakeCold, Wi.WiSnowflakeCold],
  1261: [Wi.WiSnowflakeCold, Wi.WiSnowflakeCold],
  1264: [Wi.WiSnowflakeCold, Wi.WiSnowflakeCold],
  1273: [Wi.WiNightLightning, Wi.WiDayLightning],
  1276: [Wi.WiNightThunderstorm, Wi.WiDayThunderstorm],
  1279: [Wi.WiStormShowers, Wi.WiStormShowers],
  1282: [Wi.WiStormShowers, Wi.WiStormShowers],
};

export const getConditionIcon = (code: WeatherConditions, index: 0 | 1) =>
  weatherConditionIcons[code][index];
